#!/usr/bin/env python3
"""
trc_event_audit.py — aanvullende PCAN-View TRC error/status-audit

Dit script laat de bestaande trc_summarize.py ongemoeid en rapporteert alle
records die niet als normaal Rx/Tx-CAN-frame worden herkend. Daardoor werkt het
ook wanneer de precieze PCAN-notatie voor ErrorFrame/status per versie verschilt.

Gebruik:
    python trc_event_audit.py Trace_015*.trc Trace_016*.trc Trace_017*.trc
    python trc_event_audit.py Trace_01*.trc --csv can_events

Uitvoer:
    - samenvatting per bestand
    - ontbrekende PCAN-message-nummers
    - alle error/status/onbekende records letterlijk weergegeven
    - optioneel: can_events_<trace>.csv
"""

import argparse
import csv
import glob
import os
import re
import sys
from collections import Counter

# Normaal PCAN-View 1.1 record, zoals:
#  123)  4567.8  Rx  00018B5A  7  01 00 00 0F 03 5A 8B
FRAME_RE = re.compile(
    r"^\s*(?P<num>\d+)\)\s+"
    r"(?P<t>[+-]?[\d.]+)\s+"
    r"(?P<direction>Rx|Tx)\s+"
    r"(?P<can_id>[0-9A-Fa-f]+)\s+"
    r"(?P<dlc>\d+)\s*"
    r"(?P<data>.*)$",
    re.IGNORECASE,
)

# Vangt ieder ander genummerd PCAN-record, ongeacht de verdere syntaxis.
RECORD_RE = re.compile(
    r"^\s*(?P<num>\d+)\)\s+"
    r"(?P<t>[+-]?[\d.]+)\s+"
    r"(?P<body>.*)$"
)


def natural_key(text):
    return [int(p) if p.isdigit() else p.lower()
            for p in re.split(r"(\d+)", text)]


def expand_inputs(patterns):
    found = []
    missing = []

    for pattern in patterns:
        if any(ch in pattern for ch in "*?["):
            matches = glob.glob(pattern)
            if matches:
                found.extend(matches)
            else:
                missing.append(pattern)
        elif os.path.isfile(pattern):
            found.append(pattern)
        else:
            missing.append(pattern)

    result = []
    seen = set()
    for path in sorted(found, key=natural_key):
        absolute = os.path.abspath(path)
        if absolute not in seen:
            seen.add(absolute)
            result.append(path)

    return result, missing


def classify_record(body):
    """Best-effort classificatie; de originele tekst blijft altijd behouden."""
    text = body.lower()

    rules = [
        ("bus_off",       ("bus-off", "bus off", "busoff")),
        ("error_frame",   ("errorframe", "error frame", "error-frame")),
        ("bus_heavy",     ("busheavy", "bus heavy")),
        ("bus_warning",   ("buswarning", "bus warning", "warning limit")),
        ("bus_passive",   ("error passive", "bus passive", "passive")),
        ("overrun",       ("overrun", "overflow", "queue full")),
        ("status",        ("status", "buslight", "bus light")),
        ("error",         ("error", "err")),
    ]

    for category, words in rules:
        if any(word in text for word in words):
            return category

    return "other_record"


def parse_file(path):
    frames = []
    events = []
    structural = []
    metadata = {}
    record_numbers = []

    with open(path, "r", encoding="utf-8-sig", errors="replace") as handle:
        for line_number, raw in enumerate(handle, 1):
            line = raw.rstrip("\r\n")

            if line.startswith(";"):
                if "Start time:" in line:
                    metadata["start_time"] = line.split("Start time:", 1)[1].strip()
                elif "Generated by" in line:
                    metadata["generator"] = line.split("Generated by", 1)[1].strip()
                continue

            if not line.strip():
                continue

            frame_match = FRAME_RE.match(line)
            if frame_match:
                item = frame_match.groupdict()
                num = int(item["num"])
                record_numbers.append(num)

                # Controleer ook of DLC en werkelijk aantal databytes overeenkomen.
                data_tokens = item["data"].split()
                valid_hex = all(re.fullmatch(r"[0-9A-Fa-f]{2}", token)
                                for token in data_tokens)
                dlc = int(item["dlc"])

                frames.append({
                    "num": num,
                    "t_ms": float(item["t"]),
                    "direction": item["direction"],
                    "can_id": item["can_id"].upper(),
                    "dlc": dlc,
                    "data_count": len(data_tokens),
                    "dlc_ok": valid_hex and len(data_tokens) == dlc,
                    "raw": line,
                })
                continue

            record_match = RECORD_RE.match(line)
            if record_match:
                item = record_match.groupdict()
                num = int(item["num"])
                record_numbers.append(num)
                body = item["body"]

                events.append({
                    "line_number": line_number,
                    "num": num,
                    "t_ms": float(item["t"]),
                    "category": classify_record(body),
                    "body": body,
                    "raw": line,
                })
                continue

            # Niet-genummerde, niet-commentaarregel. Meestal een onverwachte
            # header/layoutregel, maar bewaren zodat niets stil wordt weggegooid.
            structural.append({
                "line_number": line_number,
                "category": "unparsed_structural",
                "raw": line,
            })

    record_numbers = sorted(record_numbers)
    missing_numbers = []
    duplicates = []

    if record_numbers:
        counts = Counter(record_numbers)
        duplicates = sorted(num for num, count in counts.items() if count > 1)
        present = set(record_numbers)
        missing_numbers = [
            num for num in range(record_numbers[0], record_numbers[-1] + 1)
            if num not in present
        ]

    return {
        "metadata": metadata,
        "frames": frames,
        "events": events,
        "structural": structural,
        "missing_numbers": missing_numbers,
        "duplicate_numbers": duplicates,
    }


def format_number_list(values, maximum=40):
    if not values:
        return "geen"
    shown = ", ".join(str(value) for value in values[:maximum])
    if len(values) > maximum:
        shown += f", ... (+{len(values) - maximum})"
    return shown


def print_report(path, result):
    metadata = result["metadata"]
    frames = result["frames"]
    events = result["events"]
    structural = result["structural"]

    print("=" * 88)
    print(f"FILE: {path}")
    print(f"  start time       : {metadata.get('start_time', '?')}")
    print(f"  generated by     : {metadata.get('generator', '?')}")
    print(f"  normale frames   : {len(frames)}")
    print(f"  error/status     : {len(events)}")
    print(f"  structureel over : {len(structural)}")
    print(f"  ontbrekende nums : {format_number_list(result['missing_numbers'])}")
    print(f"  dubbele nums     : {format_number_list(result['duplicate_numbers'])}")

    bad_dlc = [frame for frame in frames if not frame["dlc_ok"]]
    print(f"  DLC afwijkingen  : {len(bad_dlc)}")

    if events:
        print("  categorieen      :")
        for category, count in Counter(e["category"] for e in events).most_common():
            print(f"    {category:<20} {count}")

        print("-" * 88)
        print("ERROR/STATUS RECORDS — letterlijk uit .trc")
        for event in events:
            print(
                f"  regel={event['line_number']:<7} "
                f"msg={event['num']:<7} "
                f"t={event['t_ms']:>12.3f} ms  "
                f"{event['category']:<15}  {event['body']}"
            )
    else:
        print("  Geen genummerde error/statusrecords aangetroffen.")

    if bad_dlc:
        print("-" * 88)
        print("NORMALE FRAME-REGELS MET DLC/DATA-AFWIJKING")
        for frame in bad_dlc[:50]:
            print(f"  {frame['raw']}")

    if structural:
        print("-" * 88)
        print("OVERIGE NIET-HERKENDE REGELS")
        for item in structural[:100]:
            print(f"  regel={item['line_number']:<7} {item['raw']}")
        if len(structural) > 100:
            print(f"  ... {len(structural) - 100} meer")

    print()


def write_event_csv(path, result, prefix, output_directory):
    if output_directory:
        os.makedirs(output_directory, exist_ok=True)

    basename = os.path.splitext(os.path.basename(path))[0]
    filename = f"{prefix}_{basename}.csv"
    output_path = os.path.join(output_directory or ".", filename)

    with open(output_path, "w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.writer(handle)
        writer.writerow([
            "source", "line_number", "message_number", "t_ms",
            "category", "body", "raw"
        ])
        for event in result["events"]:
            writer.writerow([
                basename,
                event["line_number"],
                event["num"],
                f"{event['t_ms']:.3f}",
                event["category"],
                event["body"],
                event["raw"],
            ])

        for item in result["structural"]:
            writer.writerow([
                basename,
                item["line_number"],
                "",
                "",
                item["category"],
                item["raw"],
                item["raw"],
            ])

    print(f"[csv] {output_path} ({len(result['events']) + len(result['structural'])} records)")


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Rapporteer PCAN-View error/status/onbekende TRC-records."
    )
    parser.add_argument("inputs", nargs="+", help=".trc-bestanden of wildcards")
    parser.add_argument("--csv", metavar="PREFIX", default=None,
                        help="exporteer events naar PREFIX_<trace>.csv")
    parser.add_argument("--out-dir", default=None,
                        help="map voor event-CSV's")
    args = parser.parse_args(argv)

    files, missing = expand_inputs(args.inputs)
    for pattern in missing:
        print(f"WAARSCHUWING: niets gevonden voor '{pattern}'", file=sys.stderr)

    if not files:
        print("FOUT: geen invoerbestanden gevonden.", file=sys.stderr)
        return 2

    print(f"Controleren van {len(files)} bestand(en):")
    for path in files:
        print(f"  - {path}")
    print()

    total_events = 0
    for path in files:
        result = parse_file(path)
        print_report(path, result)
        total_events += len(result["events"])

        if args.csv:
            write_event_csv(path, result, args.csv, args.out_dir)

    print("=" * 88)
    print(f"TOTAAL GENUMMERDE ERROR/STATUSRECORDS: {total_events}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
