#!/usr/bin/env python3
"""
trc_summarize.py  --  PCAN-View .TRC (v1.1) parser & compressor
================================================================
Purpose: turn a 12k-line CAN trace into a ~40-line summary that can be
         pasted into an AI analysis session, plus a CSV for SQL queries.

Windows-safe: expands wildcards itself, because cmd.exe does not.

Usage (cmd, PowerShell or bash - all identical):
    python trc_summarize.py Trace_00*.trc
    python trc_summarize.py Trace_00*.trc --csv can
    python trc_summarize.py Trace_00*.trc --csv can --out-dir parsed
    python trc_summarize.py Trace_001.txt Trace_002.txt

Tested against: Trace_001..006_20260925 (DAB Active Driver Plus M/M 1.5)
"""

import re
import os
import sys
import csv
import glob
import argparse
from collections import Counter, defaultdict
from statistics import mean, pstdev

# ----------------------------------------------------------------------
# 0. FILE / ARGUMENT HANDLING  (the part that broke on Windows)
# ----------------------------------------------------------------------

def natural_key(s):
    """Sort Trace_2 before Trace_10 instead of after it."""
    return [int(t) if t.isdigit() else t.lower()
            for t in re.split(r"(\d+)", s)]


def expand_inputs(patterns):
    """
    Expand shell-style wildcards ourselves.

    cmd.exe passes 'Trace_00*.trc' through literally, so relying on the
    shell (as on Linux/macOS) gives OSError [Errno 22] Invalid argument.
    Doing it here makes the script behave the same on every platform.
    """
    files, missing = [], []
    for pat in patterns:
        if any(ch in pat for ch in "*?["):
            hits = glob.glob(pat)
            if hits:
                files.extend(hits)
            else:
                missing.append(pat)
        elif os.path.isfile(pat):
            files.append(pat)
        else:
            missing.append(pat)

    # de-duplicate while keeping natural order
    seen, unique = set(), []
    for f in sorted(files, key=natural_key):
        real = os.path.abspath(f)
        if real not in seen:
            seen.add(real)
            unique.append(f)
    return unique, missing


# ----------------------------------------------------------------------
# 1. PARSING
# ----------------------------------------------------------------------

# "     1)      8972.0  Rx     00019563  7  01 00 00 0F 03 63 95"
LINE_RE = re.compile(
    r"^\s*(\d+)\)\s+([\d.]+)\s+(Rx|Tx)\s+([0-9A-Fa-f]+)\s+(\d+)\s+(.*)$"
)


class Frame:
    __slots__ = ("num", "t", "dir", "can_id", "id_hex", "ext", "dlc", "data")

    def __init__(self, num, t, direction, id_hex, dlc, data):
        self.num = num
        self.t = t                    # ms offset
        self.dir = direction
        self.id_hex = id_hex
        self.can_id = int(id_hex, 16)
        self.ext = len(id_hex) > 3    # 8 hex digits => 29-bit
        self.dlc = dlc
        self.data = data              # tuple of ints


def parse_trc(path):
    frames, meta, skipped = [], {}, 0
    # utf-8-sig strips a BOM if present; errors=replace survives junk bytes
    with open(path, "r", encoding="utf-8-sig", errors="replace") as fh:
        for raw in fh:
            if raw.startswith(";"):
                if "Start time:" in raw:
                    meta["start_time"] = raw.split("Start time:")[1].strip()
                if "Generated by" in raw:
                    meta["generator"] = raw.split("Generated by")[1].strip()
                continue
            if not raw.strip():
                continue
            m = LINE_RE.match(raw)
            if not m:
                skipped += 1
                continue
            num, t, direction, id_hex, dlc, rest = m.groups()
            try:
                data = tuple(int(b, 16) for b in rest.split())
            except ValueError:
                skipped += 1
                continue
            frames.append(Frame(int(num), float(t), direction,
                                id_hex.upper(), int(dlc), data))
    meta["skipped_lines"] = skipped
    return meta, frames


# ----------------------------------------------------------------------
# 2. ANALYSIS HELPERS
# ----------------------------------------------------------------------

def id_family(can_id):
    """Group IDs by their high 16 bits (0x0001xxxx / 0x0011xxxx / ...)."""
    return can_id & 0xFFFF0000


def analyse_family(frames):
    """Per-family statistics: DLC, period, byte variability, ID echo."""
    out = {}
    out["count"] = len(frames)
    out["dlc"] = Counter(f.dlc for f in frames)
    out["t_first"] = frames[0].t
    out["t_last"] = frames[-1].t

    deltas = [b.t - a.t for a, b in zip(frames, frames[1:])]
    if deltas:
        out["dt_mean"] = mean(deltas)
        out["dt_std"] = pstdev(deltas) if len(deltas) > 1 else 0.0
        out["dt_min"] = min(deltas)
        out["dt_max"] = max(deltas)
        out["rate_hz"] = 1000.0 / out["dt_mean"] if out["dt_mean"] else 0.0

    dom_dlc = out["dlc"].most_common(1)[0][0]
    same_dlc = [f for f in frames if f.dlc == dom_dlc]
    byte_vals = [Counter() for _ in range(dom_dlc)]
    for f in same_dlc:
        for i, b in enumerate(f.data):
            if i < dom_dlc:
                byte_vals[i][b] += 1

    out["dom_dlc"] = dom_dlc
    out["byte_profile"] = []
    for i, c in enumerate(byte_vals):
        if len(c) == 1:
            out["byte_profile"].append(f"B{i}=0x{list(c)[0]:02X} (const)")
        elif len(c) <= 4:
            top = ", ".join(f"0x{v:02X}x{n}" for v, n in c.most_common())
            out["byte_profile"].append(f"B{i}: {top}")
        else:
            out["byte_profile"].append(f"B{i}: {len(c)} distinct (variable)")

    # ID-echo check: last 2 payload bytes == low 16 bits of the ID (LE)?
    echo_ok = sum(
        1 for f in same_dlc
        if len(f.data) >= 2
        and (f.data[-1] << 8 | f.data[-2]) == (f.can_id & 0xFFFF)
    )
    out["id_echo_match"] = f"{echo_ok}/{len(same_dlc)}"

    lows = [f.can_id & 0xFFFF for f in frames]
    out["unique_low16"] = len(set(lows))
    out["low16_repeats"] = len(lows) - len(set(lows))
    return out


def find_anomalies(frames, max_report=40):
    """Frames deviating from the >=95% dominant value of a near-constant byte."""
    groups = defaultdict(list)
    for f in frames:
        groups[(id_family(f.can_id), f.dlc)].append(f)

    anomalies = []
    for grp in groups.values():
        n = grp[0].dlc
        for i in range(n):
            c = Counter(f.data[i] for f in grp if i < len(f.data))
            if not c:
                continue
            top_val, top_cnt = c.most_common(1)[0]
            if len(c) > 1 and top_cnt / len(grp) >= 0.95:
                for f in grp:
                    if i < len(f.data) and f.data[i] != top_val:
                        anomalies.append(
                            (f.t, f.num, f.id_hex, i, top_val, f.data[i], f.data)
                        )
    anomalies.sort()
    return anomalies[:max_report], len(anomalies)


# ----------------------------------------------------------------------
# 3. REPORT
# ----------------------------------------------------------------------

def report(path, meta, frames):
    print("=" * 72)
    print(f"FILE: {path}")
    print(f"  start   : {meta.get('start_time', '?')}")
    print(f"  tool    : {meta.get('generator', '?')}")
    if meta.get("skipped_lines"):
        print(f"  skipped : {meta['skipped_lines']} unparsable lines")
    if not frames:
        print("  !! no frames parsed - is this a PCAN-View v1.1 trace?")
        return
    span = (frames[-1].t - frames[0].t) / 1000.0
    print(f"  frames  : {len(frames)}   span: {span:.3f} s   "
          f"avg: {len(frames)/span if span else 0:.1f} fps")
    print(f"  dirs    : {dict(Counter(f.dir for f in frames))}")
    print(f"  id type : "
          f"{dict(Counter('29-bit' if f.ext else '11-bit' for f in frames))}")

    groups = defaultdict(list)
    for f in frames:
        groups[id_family(f.can_id)].append(f)

    print(f"  families: {len(groups)}")
    for fam in sorted(groups):
        a = analyse_family(groups[fam])
        print("-" * 72)
        print(f"  ID family 0x{fam:08X} (low 16 bits vary)   n={a['count']}")
        print(f"    DLC          : {dict(a['dlc'])}")
        print(f"    period       : {a.get('dt_mean', 0):.4f} ms "
              f"(sd {a.get('dt_std', 0):.4f}, "
              f"min {a.get('dt_min', 0):.1f}, max {a.get('dt_max', 0):.1f}) "
              f"=> {a.get('rate_hz', 0):.1f} Hz")
        print(f"    first/last   : {a['t_first']:.1f} .. {a['t_last']:.1f} ms")
        print(f"    unique ID_lo : {a['unique_low16']} "
              f"({a['low16_repeats']} repeats)")
        print(f"    ID echoed in payload : {a['id_echo_match']}")
        print(f"    byte profile (DLC {a['dom_dlc']}):")
        for line in a["byte_profile"]:
            print(f"        {line}")

    anomalies, total = find_anomalies(frames)
    print("-" * 72)
    print(f"  ANOMALIES (deviation from >=95% dominant byte value): {total}")
    for t, num, idh, idx, exp, got, data in anomalies:
        hexed = " ".join(f"{b:02X}" for b in data)
        print(f"    t={t:10.1f} #{num:<6} ID={idh}  "
              f"B{idx}: 0x{exp:02X} -> 0x{got:02X}   [{hexed}]")
    if total > len(anomalies):
        print(f"    ... {total - len(anomalies)} more")
    print()


def write_csv(path, frames, prefix, out_dir):
    base = os.path.splitext(os.path.basename(path))[0]
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    out = os.path.join(out_dir or os.path.dirname(path) or ".",
                       f"{prefix}_{base}.csv")
    with open(out, "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["source", "num", "t_ms", "dir", "can_id_hex", "can_id_dec",
                    "id_family_hex", "id_low16", "ext", "dlc",
                    "b0", "b1", "b2", "b3", "b4", "b5", "b6", "b7",
                    "payload_hex"])
        for f in frames:
            b = list(f.data) + [""] * (8 - len(f.data))
            w.writerow([
                base, f.num, f"{f.t:.1f}", f.dir, f.id_hex, f.can_id,
                f"{id_family(f.can_id):08X}", f.can_id & 0xFFFF,
                int(f.ext), f.dlc, *b[:8],
                " ".join(f"{x:02X}" for x in f.data),
            ])
    print(f"  [csv] {out}  ({len(frames)} rows)")
    return out


# ----------------------------------------------------------------------
# 4. MAIN
# ----------------------------------------------------------------------

def main(argv=None):
    ap = argparse.ArgumentParser(
        prog="trc_summarize.py",
        description="Summarize PCAN-View .TRC traces; wildcards are expanded "
                    "internally so this works in cmd.exe as well.")
    ap.add_argument("inputs", nargs="+",
                    help="trace files or wildcards, e.g. Trace_00*.trc")
    ap.add_argument("--csv", metavar="PREFIX", default=None,
                    help="also export each trace to PREFIX_<name>.csv")
    ap.add_argument("--out-dir", metavar="DIR", default=None,
                    help="directory for the CSV files")
    ap.add_argument("--max-anomalies", type=int, default=40,
                    help="max anomalies to print per file (default 40)")
    args = ap.parse_args(argv)

    files, missing = expand_inputs(args.inputs)
    for pat in missing:
        print(f"WARNING: no file matched '{pat}'", file=sys.stderr)
    if not files:
        print("ERROR: nothing to do - no input files found.", file=sys.stderr)
        print("       In cmd.exe make sure you are in the folder with the "
              "traces, or pass full paths.", file=sys.stderr)
        return 2

    print(f"Processing {len(files)} file(s):")
    for f in files:
        print(f"  - {f}")
    print()

    all_frames = {}
    for path in files:
        try:
            meta, frames = parse_trc(path)
        except OSError as e:
            print(f"ERROR reading {path}: {e}", file=sys.stderr)
            continue
        all_frames[path] = frames
        report(path, meta, frames)
        if args.csv:
            write_csv(path, frames, args.csv, args.out_dir)

    # cross-trace comparison: do the "random" ID_lo sets overlap?
    if len(all_frames) > 1:
        print("=" * 72)
        print("CROSS-TRACE COMPARISON of low-16 ID values")
        sets = {p: {f.can_id & 0xFFFF for f in fr}
                for p, fr in all_frames.items() if fr}
        names = list(sets)
        for i, a in enumerate(names):
            for b in names[i + 1:]:
                inter = len(sets[a] & sets[b])
                union = len(sets[a] | sets[b])
                pct = 100 * inter / union if union else 0
                print(f"  {os.path.basename(a):<34} vs "
                      f"{os.path.basename(b):<34} "
                      f"overlap {inter:5d} / union {union:5d} = {pct:5.1f}%")
        print("  -> high overlap beyond chance = NOT random (derived value)")
        print("  -> overlap ~ birthday-chance   = re-seeded PRNG per power-up")
    return 0


if __name__ == "__main__":
    sys.exit(main())
